services:
  personalsite:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - ./layouts:/var/www/html/layouts
      - ./pages:/var/www/html/pages
      - ./posts:/var/www/html/posts
      - ./public:/var/www/html/public
    ports:
      - 8003:80
    networks:
      - cloudflare
networks:
  cloudflare:
    external: true
